// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Infrastructure;

#nullable disable

namespace GamaLearn.ChatService.Infrastructure.Migrations
{
    [DbContext(typeof(ChatDbContext))]
    [Migration("20240902154647_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Server.Entity.ClientConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChatRoom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Connections");
                });

            modelBuilder.Entity("Server.Entity.GroupConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserIds")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d311209-1877-4315-8f3c-e995309448aa"),
                            GroupName = "Learning Session 1",
                            UserIds = "[\"471EC058-1286-4998-B59B-ACDE81ED3F30\"]"
                        },
                        new
                        {
                            Id = new Guid("2ab3db1b-6064-47e7-a1a0-dd2d0079247a"),
                            GroupName = "Learning Session 2",
                            UserIds = "[\"471EC058-1286-4998-B59B-ACDE81ED3F30\"]"
                        },
                        new
                        {
                            Id = new Guid("b7a3280c-4e33-415a-8d28-e151e163a379"),
                            GroupName = "Learning Session 3",
                            UserIds = "[\"471EC058-1286-4998-B59B-ACDE81ED3F30\"]"
                        });
                });

            modelBuilder.Entity("Server.Entity.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Delivered")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MessageType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Server.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("471ec058-1286-4998-b59b-acde81ed3f30"),
                            FirstName = "Hawariyaw",
                            LastName = "Pawulos",
                            Password = "$2a$10$X0zBaspK3Tw0o43zuxBBLuM0GQ.kNA3a6nux8EXgbXvOkKCDsmvDq",
                            UserName = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
